services:
  user-service:
    build: ./backend/user-service
    container_name: user-service
    restart: always
    ports:
      - "3001:3000"
    environment:
      DB_HOST: user-db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: users_db
      JWT_SECRET: supersecretkey
    depends_on:
      - user-db

  user-db:
    image: postgres:15
    container_name: user-postgres
    restart: always
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - user_pg_data:/var/lib/postgresql/data

volumes:
  user_pg_data:
